### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [DnB-Andrew/GTM-Visitor-Intelligence#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "apiKey" when generating the url
const viScript =  "https://" + apiKey + ".d41.co/sync/";
2) onSuccess and onFailure functions should be mentioned in sendPixel.

**Comment by DnB-Andrew** [comment]
Hi @praveena-pappu, thank you for the input. I believe I've made those changes, do I need to resubmit?

Thanks!

**Comment by praveena-pappu** [comment]
Hello,

We are seeing error "Error in encodeUriComponent. Argument uri has type number, which does not match required type string." when we run the tests. Please resolve the issue.
![Screenshot 2020-08-18 at 11 49 47 AM](https://user-images.githubusercontent.com/53495700/90553306-0589ca80-e149-11ea-947b-402a3010d16f.png)

**Comment by DnB-Andrew** [comment]
HI @praveena-pappu ,thank you for pointing that out. Although api keys given out have to be strings, I've added that change in case things change in the future.

**Comment by DnB-Andrew** [comment]
Hi @praveena-pappu any more feedback on this template?

Thanks,
Andrew

**Comment by praveena-pappu** [comment]
Hello,

We have approved it and it will be in gallery in few days.

**Comment by DnB-Andrew** [comment]
Thank you for your help here!

**Comment by DnB-Andrew** [comment]
Hi Praveena,

Any update here? I haven’t seen it pop up in the gallery yet.

Thanks,
Andrew
